version: "3.9"
services:
  nexusgate:
    build: .
    ports:
      - "4500:4500"
    volumes:
      - ./config.toml:/config.toml
      - ./storage:/storage
      - ./logs:/logs
      - ./data:/data
    restart: unless-stopped
    depends_on:
      - redis
      
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
